### PR TITLE
Fixed Dark mod in Header and Default Video layout

### PR DESCRIPTION
**Pull request by Harshcbx8**
In my Updated Code I fixed the darken mode Nav bar effects and provide the perfect visual appealing experience in both light and in dark mode. With this i also add a default Random video section where every time a random video is able to play when refresh the page.

Issue id: #22 In dark mode the Header of you MeTube is in white theme, and there is not any default component available to showcase videos in your projects is Solved!

Before Images: 
Screenshot 2024-10-19 121851

After Images: 
Screenshot 2024-10-20 155735
Screenshot 2024-10-20 155742

Hope you Like my work!

### CODE REVIEW

**Comment by MITARPALGROVER** [comment]
@Harshcbx8 the dark mode is looking really good but there's a issue in playing the video why aren't the searched videos playing in the upper video player space

Screenshot 2024-10-20 193936
Screenshot 2024-10-20 193921

**Comment by Harshcbx8** [comment]
Bro read my issue Title again, I work to fix the dark mode and build the default video layout only!! Additionally i had this feature to play videos on that layout, if you want to change according to your querry you have to just arrange the Url in java script of videos!

I have completed the work that i committed to you!

Hope you soon merge my PR

**Comment by Harshcbx8** [comment]
If you want me to fix the video error I can make another issue since this issue is related to the dark mode correction I have worked on that only and fixed the issue . I will raise another issue for video so kindly merge this request with hactoberfest-accepted label . @MITARPALGROVER

**Comment by Harshcbx8** [comment]
I again update the code please refer my code and merge the branch in your repository!

**Comment by MITARPALGROVER** [comment]
okk!!

**Pull request merged**
